[package]
name = "polyfill-library"
version = "0.1.0"
authors = []
edition = "2018"
# Remove this line if you want to be able to publish this crate as open source on crates.io.
# Otherwise, `publish = false` prevents an accidental `cargo publish` from revealing private source.
publish = false

[profile.release]
debug = true

[dependencies]
chrono = "0.4.35"
fastly = "0.9.11"
http = "1.1.0"
indexmap = { version = "2.2.5", features = ["serde"] }
lazy_static = "1.4.0"
nodejs-semver = "4.0.0"
regex = "1.10.3"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
urlencoding = "2.1.3"
