[package]
name = "polyfill-library"
version = "0.1.0"
authors = []
edition = "2018"
# Remove this line if you want to be able to publish this crate as open source on crates.io.
# Otherwise, `publish = false` prevents an accidental `cargo publish` from revealing private source.
publish = false

[profile.release]
debug = true

[dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
chrono = "0.4.31"
fastly = "0.9.9"
http = "1.0.0"
http-range = "0.1.5"
httpdate = "1.0.3"
human_format = "1.0.3"
humansize = "2.1.3"
indexmap = "2.1.0"
maud = "0.25.0"
nodejs-semver = "3.2.0"
regex = "1.10.2"
semver = "1.0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
sha2 = "0.10.8"
thousands = "0.2.0"
urlencoding = "2.1.3"
