name: Deploy to production
on:
  release:
    types: [created]
env:
  eu_app: origami-polyfill-service-eu
  us_app: origami-polyfill-service-us
  terraform_version: '1.1.7'
  terraform_working_dir: 'fastly/terraform/'
  fastly_vcl_service_id: 4E1GeTez3EFH3cnwfyMAog
  fastly_compute_service_id: 3AfcolkTD4KUfkrKGIYZ4T
  domain: cdn.polyfill.io
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 12.x
    - name: Cache node modules
      uses: actions/cache@v3.0.1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: npm ci
    - run: npm ci && npm run build
      working-directory: fastly/c-at-e
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:
        same-branch-only: false
    - run: git push https://heroku:${{ secrets.HEROKU_AUTH_TOKEN }}@git.heroku.com/${{ env.eu_app }}.git HEAD:refs/heads/main --force
    - run: git push https://heroku:${{ secrets.HEROKU_AUTH_TOKEN }}@git.heroku.com/${{ env.us_app }}.git HEAD:refs/heads/main --force
    - name: Remove the development and staging terraform configuration overrides
      run: rm -f terraform.tfstate fastly/terraform/dev_override.tf fastly/terraform/qa_override.tf fastly/terraform/domains_override.tf
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Terraform Import Fastly VCL Service'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'import'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
        args: 'fastly_service_vcl.app ${{ env.fastly_vcl_service_id }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: 'Terraform Import Fastly Compute Service'
      if: steps.witness.outputs.cache-hit != 'true'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'import'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: false
        args: 'fastly_service_compute.app ${{ env.fastly_compute_service_id }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: 'Terraform Import Fastly Service Dictionary Top-pops Config Items'
      if: steps.witness.outputs.cache-hit != 'true'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'import'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
        args: 'fastly_service_dictionary_items.toppops_config_items "${{ env.fastly_vcl_service_id }}/446GW5am9tyUvsz9qPQ1jW"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: 'Terraform Import Fastly Service Dictionary Compute At Edge Config Items'
      if: steps.witness.outputs.cache-hit != 'true'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'import'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
        args: 'fastly_service_dictionary_items.compute_at_edge_config_items "${{ env.fastly_vcl_service_id }}/0YxAHTtZA6o2U7ZKVcbbL1"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
        args: '-out=plan.tfplan'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
        args: '--auto-approve'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: "Add the http logger for Top of the POPS"
      run: "npm run toppops"
      env:
        FASTLY_API_KEY_POLYFILL_ACCOUNT: ${{ secrets.FASTLY_API_KEY_PROD }}
        FASTLY_SERVICE_ID_PROD: ${{ secrets.FASTLY_SERVICE_ID_PROD }}

  create-change-log:
    needs: [deploy-to-production]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Financial-Times/change-api-action@v1
        name: Create new change log
        with:
          change-api-key: ${{ secrets.CHANGE_API_KEY }}
          system-code: "origami-polyfill-service"
          environment: prod
          slack-channels: "ft-changes,origami-deploys"

  scale-up:
    needs: [deploy-to-production]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash .github/workflows/create-netrc.sh
        env:
          HEROKU_LOGIN: ${{ secrets.HEROKU_LOGIN }}
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      - run: heroku ps:scale web=10:performance-l --app ${{ env.eu_app }}
      - run: heroku ps:scale web=10:performance-l --app ${{ env.us_app }}
      # Wait for the applications to be fully booted before finishing the job
      - run: sleep 60

  purge-cdn:
    needs: [scale-up]
    runs-on: ubuntu-latest
    timeout-minutes: 200
    steps:
      - run: >-
          for PURGE_GROUP in `seq 0 999`;
          do
            curl --fail --show-error --silent -X POST -H "Fastly-Key: ${{ secrets.FASTLY_API_KEY_PROD }}" "https://api.fastly.com/service/${{ env.fastly_vcl_service_id }}/purge/PurgeGroup$PURGE_GROUP"
            sleep 5
          done

  scale-down:
    needs: [purge-cdn]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash .github/workflows/create-netrc.sh
        env:
          HEROKU_LOGIN: ${{ secrets.HEROKU_LOGIN }}
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      # Wait for the cache to build back up before scaling back down
      - run: sleep 300
      - run: heroku ps:scale web=1:performance-l --app ${{ env.eu_app }}
      - run: heroku ps:scale web=1:performance-l --app ${{ env.us_app }}
