name: Deploy to production
on:
  release:
    types: [created]
env:
  terraform_version: 'latest'
  terraform_working_dir: 'fastly/terraform/'
  fastly_service_id: ${{ secrets.FASTLY_SERVICE_ID_PROD }}
  domain: cdn.polyfill.io
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: Login to Heroku Container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN }}
      run: heroku container:login
    - name: Build Docker image
      run: docker build . --tag registry.heroku.com/origami-polyfill-service-eu/web --tag registry.heroku.com/origami-polyfill-service-us/web
    - name: Push Docker image to Heroku eu
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN }}
      run: docker push registry.heroku.com/origami-polyfill-service-eu/web
    - name: Push Docker image to Heroku us
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN }}
      run: docker push registry.heroku.com/origami-polyfill-service-us/web
    - name: Release eu
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN }}
      run: heroku container:release -a origami-polyfill-service-eu web
    - name: Release us
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN }}
      run: heroku container:release -a origami-polyfill-service-us web
    - name: Remove the development and staging terraform configuration overrides
      run: rm -f terraform.tfstate fastly/terraform/dev_override.tf fastly/terraform/qa_override.tf fastly/terraform/domains_override.tf
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Terraform Import Fastly Service'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'import'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
        args: 'fastly_service_v1.app ${{ env.fastly_service_id }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: 'Terraform Import Fastly Service Dictionary Items'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'import'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
        args: 'fastly_service_dictionary_items_v1.items "${{ env.fastly_service_id }}/3t3bjgcYBnC8nfCHM60Hay"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
        args: '-out=plan.tfplan'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_version: ${{ env.terraform_version }}
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: ${{ env.terraform_working_dir }}
        tf_actions_comment: true
        args: '--auto-approve'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY_PROD }}
    - name: "Add the http logger for Top of the POPS"
      run: "npm run toppops"
      env:
        FASTLY_API_KEY_POLYFILL_ACCOUNT: ${{ secrets.FASTLY_API_KEY_PROD }}
        FASTLY_SERVICE_ID_PROD: ${{ secrets.FASTLY_SERVICE_ID_PROD }}

  create-change-log:
    needs: [deploy-to-production]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Financial-Times/change-api-action@v1
        name: Create new change log
        with:
          change-api-key: ${{ secrets.CHANGE_API_KEY }}
          system-code: "origami-polyfill-service"
          environment: prod
          slack-channels: "ft-changes,origami-deploys"
