name: npm audit fix

on:
  schedule:
    - cron: 0 0 * * * # Runs at 00:00 UTC every day

# on:
#   push:
#     branches:
#       - $default-branch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ybiquitous/npm-audit-fix-action@v2.1.6
        with:
          github_token: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
          # branch: "npm-audit-fix"
          # default_branch: $default-branch
          # commit_title: "chore(deps): npm audit fix"
